### ISSUE TITLE
GitHub is not detecting your LICENSE

### ISSUE THREAD

**Issue by mithro** [sgherbst/anasymod#1]
GitHub seems to be unable to understand the LICENSE file you have in this repository. See https://help.github.com/en/articles/licensing-a-repository#detecting-a-license for more information on how GitHub does the detection process.

It looks like your LICENSE is BSD / MIT style?

**Comment by sgherbst** [comment]
Thanks for the feedback!  This project is released under Infineon’s open source license, which is similar to the 3-clause BSD license, but not exactly the same.  I don’t think that GitHub detects this specific license, sorry :-(
